version : '3'
services:
 petclinic:
  image: eliawad80/petclinic:elias
  ports:
    - "8080:8080"
  environment:
    - PETCLICNIC_DB=petclinic
    - PETCLICNIC_DBUSER=petclinic
    - PETCLICNIC_PASSWORD=petclinic

 
 mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=petclinic
    - MYSQL_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
    - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
